# Generated by Django 4.1 on 2022-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('middle_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('grade', models.IntegerField()),
                ('parent_number', models.IntegerField()),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
