# Generated by Django 4.1 on 2022-09-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_studentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendancedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
