# Generated by Django 4.1 on 2022-09-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancedetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancedetail',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='attendancedetail',
            old_name='student_id',
            new_name='S_id',
        ),
        migrations.RenameField(
            model_name='attendancedetail',
            old_name='status',
            new_name='Status',
        ),
    ]
