# Generated by Django 4.1 on 2022-09-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_date_attendancedetail_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancedetail',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='attendancedetail',
            old_name='Status',
            new_name='status',
        ),
    ]
