# Generated by Django 4.1 on 2022-09-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_date_attendancedetail_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='grade',
            field=models.CharField(max_length=30),
        ),
    ]
